scriptencoding utf-8

set tabstop=4
set softtabstop=4
set shiftwidth=4
set expandtab

set statusline=[%{&fenc!=''?&fenc:&enc}][%{&ff}]%F%m%r%h%w[%Y]%=[%l,%v][%3p%%]
set laststatus=2

set list
set listchars=trail:\ ,tab:>-,extends:<
