scriptencoding utf-8

set tabstop=4
set softtabstop=4
set shiftwidth=4
set expandtab
set nowrap
set number
set scrolloff=0

set fileformats=unix,dos

"set statusline=[%{&fenc!=''?&fenc:&enc}][%{&ff}]%F%m%r%h%w[%Y]%=[%l,%v][%3p%%]
set laststatus=2

set list
set listchars=trail:\ ,tab:>-,extends:<

set ignorecase
set hlsearch

set diffopt=filler,vertical,context:100000

set directory=~/.cache/vim/swap
set backupdir=~/.cache/vim/backup
set undodir=~/.cache/vim/undo

nmap <ESC><ESC> :nohlsearch<cr>

nmap <DOWN>  :cnext<cr>
nmap <UP>    :cprev<cr>
nmap <LEFT>  :colder<cr>
nmap <RIGHT> :cnewer<cr>

nmap <A-LEFT>  :diffget<cr>
nmap <A-RIGHT> :diffput<cr>
nmap <A-DOWN>  ]czz
nmap <A-UP>    [czz

nmap <C-W><C-O> :tabe %<cr>

" Mark
nmap <unique> <silent> g/ <Plug>MarkSet
vmap <unique> <silent> g/ <Plug>MarkSet
nmap <unique> <silent> g. <Plug>MarkClear
nmap <unique> <silent> gr <Plug>MarkRegex
nmap <unique> <silent> g? :<C-u>call mark#ClearAll()<CR>

imap <C-]> <C-R>+

vmap / y/<C-R>"<CR>

source $VIMLOCAL/dein.vimrc
source $VIMLOCAL/perl.vimrc
source $VIMLOCAL/lightline.vimrc
source $VIMLOCAL/cscope.vimrc

colorscheme molokai

let g:go_fmt_command="goimports"
